title: Sparti theme
description: This is a Jekyll theme for sparti.se GitHub Pages
contact:
  mail: contact@sparti-theme.com
google_analytics:
remote_theme: turbotobbe/jekyll-theme-sparti
plugins:
  - jekyll-seo-tag
