title: Sparti
description: This is a Jekyll theme for sparti.se to be used in GitHub Pages.
orgnr: 123456-7890

footer:
  navigation:
    - url: /lorem.html
    - url: /platon.html
    - url: /selma.html

contact:
  mail: contact@example.com
  phone:
    href: "+46731234567"
    text: "073 123 45 67"
  # adress:
  #   street: Storgatan 123
  #   postal: 58 123 Ankeborg

copyright:
  year: 2020
  org: Sparti AB

collections:
  people:
    output: false

defaults:
  - scope:
      path: ""
    values:
      locale: sv_SE
      image:
        path: /assets/images/SPARTI_logo_1200x1200.jpg
        width: 1200
        height: 1200

google_analytics:

remote_theme: turbotobbe/jekyll-theme-sparti
plugins:
  - jekyll-seo-tag
