title: Sparti
description: This is a Jekyll theme for sparti.se to be used in GitHub Pages.

footer:
  navigation:
    - url: /lorem.html
    - url: /platon.html
    - url: /selma.html

contact:
  mail: contact@example.com
  phone:
    href: "+46731234567"
    text: "073 123 45 67"

copyright:
  year: 2020
  org: Sparti AB

defaults:
  - scope:
      path: ""
    values:
      locale: sv_SE
      image:
        path: /assets/images/SPARTI_logo_white_color.jpg
        width: 1754
        height: 1400


google_analytics:

remote_theme: turbotobbe/jekyll-theme-sparti
plugins:
  - jekyll-seo-tag
